name: real_acres_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  splashscreen: ^1.2.0
  provider: ^3.0.0+1
  geolocator: ^5.2.1
  google_maps_flutter: ^0.5.11
  cloud_firestore: ^0.13.0+1
  flutter_map: ^0.8.2
  location: ^2.3.5
  flutter_spinkit: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  fonts:
    - family: yantramanav
      fonts:
        - asset: fonts/Yantramanav-Regular.ttf
